version: '3.8'

services:
  postgresql:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - minha_rede

  adminer:
    image: adminer
    container_name: meu_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - minha_rede

volumes:
  postgresql_data:
    driver: local

networks:
  minha_rede:
    driver: bridge
